### ISSUE TITLE
Project_1 Grading Requirements_ Checklist

### ISSUE THREAD

**Issue by saiaungkyawmaw** [Bug-Busters-UNCC-ITSC3155/Project1#2]
- [x] DefineProblem - Identify and define a problem threshold

- [x] DesignSolution - Design a solution using appropriate tools / technologies / strategies and applying appropriate design/modeling principles threshold

- [x] Implementation - Implement a solution that reflects the design

- [x] TestingSolution, verification and validation

- [x] UserStories - Consider diverse audiences, users, and stakeholders when defining the problem, its context, and the requirements threshold

**Comment by saiaungkyawmaw** [comment]
All checked-out
